version: "3"
services:
    node-express-docker:
        environment:
            - NODE_ENV=development
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./:/dist
        container_name: node-express-docker
        expose:
            - "31500"
        ports:
            - "31500:31500"
        command: npm run